name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Setup PHP version
      uses: shivammathur/setup-php@v1
      with:
        php-version: '7.3'

    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Create .env file
      run: cp .env.example .env

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Setup Composer cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Verify WP-CLI environment
      run: |
        wp-content/vendor/bin/wp cli info --debug
        wp-content/vendor/bin/wp config list

    - name: Prepare environment
      run: composer prepare

    - name: Run WordPress server
      run: wp server > /dev/null 2>&1 &

    - name: Run test suite
      run: composer test
