name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create empty .env file
      run: touch .env

      - name: Set environment variables
        uses: allenevans/set-env@v1.0.0
        with:
          DB_HOST: 'localhost'
          DB_NAME: 'asv3_test'
          DB_PORT: 3306
          DB_USER: 'root'
          DB_PASS: 'root'

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Prepare environment
      run: composer prepare

    - name: Run test suite
      run: composer test
