name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create .env file
      run: |
        touch .env
        echo "DB_HOST: 'localhost'" >> .env
        echo "DB_NAME: 'asv3_test'" >> .env
        echo "DB_PORT: 3306" >> .env
        echo "DB_USER: 'root'" >> .env
        echo "DB_PASS: 'root'" >> .env

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Verify WP-CLI environment
      run: wp-content/vendor/bin/wp cli info --debug

    - name: Prepare environment
      run: composer prepare

    - name: Run test suite
      run: composer test
